/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distribuidos.sistemas.trabalho.telas;

import distribuidos.sistemas.trabalho.classes.Cep;
import distribuidos.sistemas.trabalho.classes.Cidade;
import distribuidos.sistemas.trabalho.classes.Contato;
import distribuidos.sistemas.trabalho.dao.AlterarContato;
import distribuidos.sistemas.trabalho.dao.Conexao;
import distribuidos.sistemas.trabalho.dao.InserirCep;
import distribuidos.sistemas.trabalho.dao.InserirCidade;
import distribuidos.sistemas.trabalho.dao.InserirContato;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Leonardo
 */
public class TelaAlterarContato extends javax.swing.JFrame {
    private Contato contato;
    private Cep cep;
    private Cidade cidade;

    public Contato getContato() {
        return contato;
    }

    public void setContato(Contato contato) {
        this.contato = contato;
    }

    public Cep getCep() {
        return cep;
    }

    public void setCep(Cep cep) {
        this.cep = cep;
    }

    public Cidade getCidade() {
        return cidade;
    }

    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    /**
     * Creates new form TelaAlterarCliente
     */
    public TelaAlterarContato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param codigo
     * @return 
     * @throws java.sql.SQLException
     */
    @SuppressWarnings("unchecked")
    
    public Contato getPorCodigo(Integer codigo) throws SQLException {
        String sql = "SELECT contato.codigo, contato.nome, contato.email, contato.complemento, contato.endereco, contato.emailalaternativo " +
                    "FROM contato" +
                    "WHERE codigo = " + "'" + codigo + "'" + ";";
        Statement st = Conexao.getStatement();
        ResultSet rs = st.executeQuery(sql);
        Contato c = null;
        if (rs.next()) {
            c = new Contato();
            c.setCodigo(rs.getInt("codigo"));
            c.setNome(rs.getString("nome"));
            c.setEmail(rs.getString("email"));
            //c.setCep(cep);
            c.setComplemento(rs.getString("complemento"));
            c.setEndereco(rs.getString("endereco"));
            c.setEmailAlternativo(rs.getString("emailalaternativo"));
        }
        return c;    
    } 
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        textComplemento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textCep = new javax.swing.JTextField();
        textEmailAlt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textCidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        doAlterar = new javax.swing.JButton();
        textEstado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textEndereco = new javax.swing.JTextField();
        textCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Alterar Contato");

        jLabel9.setText("Cidade");

        textCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textCepKeyReleased(evt);
            }
        });

        jLabel3.setText("Nome:");

        jLabel10.setText("Estado");

        textCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textCidadeKeyReleased(evt);
            }
        });

        jLabel5.setText("E-mail alternativo:");

        doAlterar.setText("Alterar");
        doAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doAlterarActionPerformed(evt);
            }
        });

        jLabel6.setText("Endereço");

        jLabel4.setText("E-mail:");

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("CEP:");

        jLabel7.setText("Complemento");

        textCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Insira codigo e cidade para alterar.");

        jLabel11.setText("Codigo:");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(textNome)
                        .addComponent(textEmail)
                        .addComponent(jLabel5)
                        .addComponent(textEmailAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(textEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Cancelar)
                        .addGap(31, 31, 31)
                        .addComponent(doAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(textEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCep, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(65, 65, 65))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscar)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(buscar))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textEmailAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(textEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(textCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doAlterar)
                    .addComponent(Cancelar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCepKeyReleased
        /*ListarCep lc = new ListarCep();
        try {
            cep = lc.buscarCep(Integer.parseInt(textCep.getText()));
            if(cep!=null){
                textCidade.setEditable(false);
                textEstado.setEditable(false);
                textCidade.setText(cep.getCidade().getNome());
                textEstado.setText(cep.getCidade().getEstado());
                cidade = cep.getCidade();
            }else{
                textCidade.setEditable(true);
                textEstado.setEditable(true);
            }
        }catch (SQLException ex) {
            cep = null;
            cidade = null;
        }*/
    }//GEN-LAST:event_textCepKeyReleased

    private void textCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCidadeKeyReleased
        /*ListarCidade lc = new ListarCidade();
        try {
            cidade = lc.buscarCidade(textCidade.getText());
            if(cidade!=null){
                textEstado.setEditable(false);
                textEstado.setText(cidade.getEstado());
            }else{
                textEstado.setEditable(true);
            }
        }catch (SQLException ex) {
            cidade = null;
        }*/
    }//GEN-LAST:event_textCidadeKeyReleased

    private void doAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doAlterarActionPerformed
        contato = new Contato();
        contato.setNome(textNome.getText());
        if(contato.getNome().isEmpty()){
            JOptionPane.showMessageDialog(this, "Campo nome é obrigatório!");
            return;
        }
        contato.setEmail(textEmail.getText());
        if(contato.getEmail().isEmpty()){
            JOptionPane.showMessageDialog(this, "Campo email é obrigatório!");
            return;
        }
        contato.setEmailAlternativo(textEmailAlt.getText());
        contato.setEndereco(textEndereco.getText());
        contato.setComplemento(textComplemento.getText());

        if(cep == null){
            cep = new Cep();
            cep.setCep(Integer.parseInt(textCep.getText()));
            if(textCep.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Campo cep é obrigatório!");
                return;
            }
            if(cidade == null ){
                cidade = new Cidade();
                cidade.setNome(textCidade.getText());
                if(textCidade.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Campo cidae é obrigatório!");
                    return;
                }
                cidade.setEstado(textEstado.getText());
                if(textEstado.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Campo estado é obrigatório!");
                    return;
                }
                InserirCidade ic = new InserirCidade();
                ic.setCidade(cidade);
                if(!ic.inserir()){
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar cidade!");
                    return;
                }
            }
            cep.setCidade(cidade);
            InserirCep ic = new InserirCep();
            if(!ic.inserir(cep)){
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar cep!");
                return;
            }
        }
        contato.setCep(cep);
        AlterarContato ac = new AlterarContato();
        if(ac.inserir(contato)){
            JOptionPane.showMessageDialog(this, "Cadastrado com sucesso!");
            limparCampos();
            cep = null;
            cidade = null;
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar");
        }

    }//GEN-LAST:event_doAlterarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void textCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodigoActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        Integer codigo = Integer.parseInt(textCodigo.getText());

        Contato c = null;
        try {
            c = this.getPorCodigo(codigo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Deu erro. "+
                   ex.getLocalizedMessage());
        }


        if (c != null) {
            textNome.setText(c.getNome());
            textCep.setText(c.getCep().toString());
            textComplemento.setText(c.getComplemento());
            textEmail.setText(c.getEmail());
            textEmailAlt.setText(c.getEmailAlternativo());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Código Não encontrado");
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void limparCampos(){
        textCep.setText("");
        textCidade.setText("");
        textComplemento.setText("");
        textEmail.setText("");
        textEmailAlt.setText("");
        textEndereco.setText("");
        textEstado.setText("");
        textNome.setText("");
        textCep.setEditable(true);
        textCidade.setEditable(true);
        textEstado.setEditable(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton buscar;
    private javax.swing.JButton doAlterar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textCep;
    private javax.swing.JTextField textCidade;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textComplemento;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textEmailAlt;
    private javax.swing.JTextField textEndereco;
    private javax.swing.JTextField textEstado;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables
}
